feat: add PHP 8.4 packages
loophp/php-src-nix pull request #196
Opened 2024-12-23 07:48 UTC by gaelreyrol

Hi @drupol,

It's been a long time since this repository has not been updated. Therefore PHP 8.4 has been released last month and I added it because I am using a lot this repository :wink:.

I hope those changes match your requirements!

Regards

2024-12-23 08:03 UTC, drupol approved these changes
Thank you Gael!

Indeed, I don't have much time to maintain it properly, I would suggest to use nixpkgs directly instead.

Your changes are good for me, let's merge them and move on.

2024-12-23 08:25 UTC, drupol requested changes

2024-12-23 08:25 UTC, drupol commented on src/overlays/snapshot.nix
>        version = "8.4.999-${inputs.php-src-master.shortRev}";
This needs to be updated

2024-12-23 18:43 UTC, gaelreyrol commented
I updated the PR to also update active, archive and snapshots but I could not managed to build archived ones because of libxml 2.12 and 2.13 incompatibility. Maybe you can help with that or maybe archives that does not build should be marked as broken?

2024-12-23 18:44 UTC, gaelreyrol commented on src/overlays/snapshot.nix
>        version = "8.4.999-${inputs.php-src-master.shortRev}";
done

2025-02-01 10:32 UTC, gaelreyrol commented
@drupol Should I do something particular to expect it to be approved/merged?

2025-02-01 10:51 UTC, merged

2025-02-01 10:51 UTC, drupol commented
Hello @gaelreyrol, sorry for the delay, I would not advise using this project any more, I barely maintain it.

If you're willing to improve things, let me know and I'll make you a maintainer too.